extends Control
## OPENAI IM COMING FOR YOUR ASS
## THIS WILL BE SUPRE ADVANCED AI
## THAT CAN MAKE SUPER POOP JOKES
## AT LIGHT SPEED AND CONSUME
## 5 QUADRILLION GALLONS OF WATER PER NANOSECOND
## AND USE UP 67 ZILLIONS TERAWATTS OF POWER
## AND USE UP LIKE FUCKING 8 BILLION DOLLARS WORTH OF RAM
## CONSEQUENTLY DESTROYING THE FUCKING PLANET
class_name QMatrix

func _ready() -> void:
	Global.q_matrix = self
